import { Leaf, ClipboardCheck, Droplets, Recycle, Truck, FlaskConical, Globe2, Trees, Waves, Gauge, Zap } from 'lucide-react';

export const services = [
  {slug:'cevre-yonetimi',icon:Leaf,title:'Çevre Yönetimi',summary:'Çevre mevzuatı, izin/lisans, beyan, saha denetimi ve çevresel yükümlülüklerin bütüncül yönetimi.',intro:'İşletmelerin çevre mevzuatına uyumunu yalnızca evrak takibi olarak değil, sahadaki gerçek proses ve risklerle birlikte yönetiyoruz.',sections:[['Kapsam','Çevre izin ve lisans süreçleri, mevzuat takibi, resmi bildirimler, iç tetkikler, çevresel risk değerlendirmeleri, uygunsuzluk takibi ve denetim hazırlıkları tek bir yönetim yaklaşımı altında ele alınır.'],['Nasıl çalışıyoruz?','Tesisi ve faaliyetleri yerinde değerlendirir, yükümlülük envanteri çıkarır, yıllık çalışma planı oluşturur ve her yükümlülüğü sorumlusu ile terminine bağlarız. Amaç, işletmenin her an denetime hazır, izlenebilir ve sürdürülebilir bir çevre yönetim sistemine sahip olmasıdır.'],['İşletmeye katkısı','İdari risklerin azalması, süreçlerin zamanında yürütülmesi, saha uygulamalarının güçlenmesi ve çevresel performansın ölçülebilir hale gelmesi sağlanır.']]},
  {slug:'ced-yonetimi',icon:ClipboardCheck,title:'ÇED Yönetimi',summary:'Yeni yatırım ve kapasite değişikliklerinde ÇED kapsamı, başvuru ve taahhüt süreçlerinin yönetimi.',intro:'Yatırımın planlama aşamasından işletmeye geçişine kadar ÇED yükümlülüklerini proje gerçekliğiyle birlikte yönetiyoruz.',sections:[['Kapsam','ÇED Yönetmeliği kapsam değerlendirmesi, proje tanıtım dosyası/ÇED süreçleri, kurum görüşleri, revizyonlar ve karar sonrası taahhütlerin takibi yürütülür.'],['Proje yaklaşımı','Kapasite, proses, alan, hammadde ve emisyon/atıksu/atık kaynakları birlikte değerlendirilir. Böylece başvuru dokümanı ile sahadaki gerçek yatırım arasında uyum korunur.'],['İşletme dönemi','ÇED kararında verilen taahhütler bir kontrol listesine dönüştürülür ve işletme aşamasında periyodik olarak izlenir.']]},
  {slug:'atiksu-yonetimi',icon:Droplets,title:'Atıksu Yönetimi',summary:'Atıksu kaynakları, arıtma, analiz, deşarj ve izin süreçlerinin teknik yönetimi.',intro:'Atıksuyu yalnızca bir deşarj noktası olarak değil, proses performansı ve su verimliliğiyle ilişkili bir yönetim konusu olarak ele alıyoruz.',sections:[['Kapsam','Atıksu kaynaklarının belirlenmesi, karakterizasyon, numune/analiz planları, arıtma tesisi kontrolleri, deşarj standartları ve izin süreçleri değerlendirilir.'],['Teknik izleme','Debi, parametre trendleri, arıtma verimi ve kimyasal tüketimler izlenerek uygunsuzlukların kaynağı araştırılır.'],['İyileştirme','Kaynakta azaltım, proses optimizasyonu, geri kullanım ve arıtma performansını artıracak teknik aksiyonlar önceliklendirilir.']]},
  {slug:'atik-yonetimi',icon:Recycle,title:'Atık Yönetimi',summary:'Atığın oluşumundan lisanslı tesise teslimine kadar tüm sürecin mevzuata uygun yönetimi.',intro:'Atık yönetimini sahada başlayan, kayıt ve beyanla tamamlanan uçtan uca bir sistem olarak kuruyoruz.',sections:[['Kapsam','Atık kodlarının belirlenmesi, kaynağında ayrı toplama, geçici depolama, etiketleme, taşıma, lisanslı tesis seçimi ve beyan süreçleri yönetilir.'],['Saha düzeni','Atık alanlarının uygunluğu, konteyner/ambalaj seçimi, tehlikeli-tehlikesiz atık ayrımı ve çalışan farkındalığı kontrol edilir.'],['Kaynak verimliliği','Atık miktarları analiz edilerek azaltım, yeniden kullanım ve geri kazanım fırsatları belirlenir.']]},
  {slug:'tmgd',icon:Truck,title:'TMGD',summary:'Tehlikeli Madde Güvenlik Danışmanlığı kapsamında ADR süreçleri, kayıt ve operasyon uyumunun takibi.',intro:'Tehlikeli maddelerin taşıma zincirindeki yükümlülüklerini operasyonla birlikte yöneterek riskleri azaltıyoruz.',sections:[['Kapsam','ADR kapsam analizi, tehlikeli madde envanteri, taşıma evrakları, ambalajlama/etiketleme, yükleme-boşaltma kontrolleri ve yıllık raporlama süreçleri yürütülür.'],['Saha uygulaması','Gönderici, alıcı, yükleyen, boşaltan ve taşıyan tarafların sorumlulukları operasyon akışında kontrol edilir.'],['Süreklilik','Değişen faaliyetler ve yeni maddeler düzenli olarak sisteme dahil edilir, personel farkındalığı güncel tutulur.']]},
  {slug:'kdu',icon:FlaskConical,title:'KDU',summary:'Kimyasal değerlendirme, sınıflandırma, kayıt ve uyumluluk süreçlerinin yönetimi.',intro:'Kimyasal mevzuat yükümlülüklerini ürün, hammadde ve tedarik zinciri bilgileriyle birlikte ele alıyoruz.',sections:[['Kapsam','Kimyasal envanter, güvenlik bilgi formları, sınıflandırma/etiketleme, kayıt yükümlülükleri ve tedarikçi dokümanları kontrol edilir.'],['Veri kalitesi','Kimyasal bilgilerin güncelliği, kullanım miktarları ve mevzuat eşikleri düzenli olarak değerlendirilir.'],['Uyum yönetimi','Eksik dokümanlar, güncelleme ihtiyaçları ve yasal aksiyonlar sorumlular ve terminlerle takip edilir.']]},
  {slug:'esg',icon:Globe2,title:'ESG',summary:'Çevresel, sosyal ve yönetişim performansının veri temelli ölçümü ve raporlama altyapısı.',intro:'ESG çalışmalarını sahadaki gerçek verilerle beslenen, ölçülebilir ve kurumsal kararları destekleyen bir sisteme dönüştürüyoruz.',sections:[['Çevresel boyut','Enerji, su, atık, emisyon, iklim ve kaynak verimliliği göstergeleri tanımlanır ve veri sahipliği oluşturulur.'],['Yönetim yapısı','Hedefler, sorumluluklar, veri doğrulama ve yönetim gözden geçirme mekanizmaları oluşturulur.'],['Raporlama hazırlığı','Göstergeler zaman serisi halinde izlenir; eksik veri, risk ve iyileştirme alanları raporlamadan önce belirlenir.']]},
  {slug:'karbon-ayak-izi',icon:Trees,title:'Karbon Ayak İzi',summary:'Kurumsal sera gazı envanteri, hesaplama, doğrulama hazırlığı ve azaltım yol haritası.',intro:'Karbon ayak izini tek bir sayı değil, azaltım kararlarını yönlendiren kurumsal bir performans göstergesi olarak ele alıyoruz.',sections:[['Envanter','Doğrudan ve dolaylı emisyon kaynakları belirlenir; yakıt, elektrik, proses, lojistik ve diğer faaliyet verileri toplanır.'],['Hesaplama','İlgili standart ve metodolojilere uygun emisyon faktörleriyle hesaplama yapılır, veri kalitesi ve belirsizlikler değerlendirilir.'],['Azaltım','En yüksek emisyon kaynakları önceliklendirilir ve uygulanabilir azaltım projeleri için yol haritası hazırlanır.']]},
  {slug:'su-ayak-izi',icon:Waves,title:'Su Ayak İzi',summary:'Su kullanımının miktar, kaynak ve çevresel etki boyutuyla değerlendirilmesi.',intro:'Su tüketimini yalnızca sayaç değeri olarak değil, havza riski ve proses etkisiyle birlikte analiz ediyoruz.',sections:[['Su dengesi','Su kaynakları, kullanım noktaları, kayıplar, geri kullanım ve deşarjlar sistematik olarak haritalanır.'],['Etki yaklaşımı','Tüketimin gerçekleştiği bölgenin su stresi ve kullanımın çevresel etkisi değerlendirmeye dahil edilir.'],['Hedefler','Öncelikli tüketim noktaları için azaltım ve geri kullanım hedefleri belirlenir.']]},
  {slug:'su-verimliligi',icon:Gauge,title:'Su Verimliliği',summary:'Su tüketimini azaltma, kayıpları önleme ve yeniden kullanım fırsatlarının belirlenmesi.',intro:'Tesisin su kullanımını proses bazında analiz ederek teknik ve operasyonel tasarruf fırsatlarını ortaya çıkarıyoruz.',sections:[['Analiz','Sayaçlar, tüketim verileri, proses akışları ve kayıp noktaları incelenerek su dengesi oluşturulur.'],['Fırsatlar','Nozul, yıkama, soğutma, geri kullanım, yağmur suyu ve proses optimizasyonu gibi seçenekler değerlendirilir.'],['Uygulama planı','Her aksiyon tasarruf potansiyeli, yatırım ihtiyacı ve geri dönüş süresi açısından önceliklendirilir.']]},
  {slug:'enerji-yonetimi',icon:Zap,title:'Enerji Yönetimi',summary:'Enerji tüketimlerinin izlenmesi, performans analizi ve verimlilik iyileştirmelerinin yönetimi.',intro:'Enerji verisini çevresel performans ve maliyet yönetimiyle birlikte ele alarak sürekli iyileştirme sistemi kuruyoruz.',sections:[['Enerji profili','Elektrik, doğal gaz, yakıt ve diğer enerji tüketimleri proses ve ekipman bazında analiz edilir.'],['Performans','Baz tüketimler, yoğunluk göstergeleri ve önemli enerji kullanım alanları belirlenir; dönemsel sapmalar izlenir.'],['Verimlilik','Motorlar, basınçlı hava, ısıtma-soğutma, proses ısısı, aydınlatma ve yenilenebilir enerji fırsatları teknik ve ekonomik açıdan değerlendirilir.']]},
];

export const ministryUrl='https://www.csb.gov.tr/';
export const ucbsUrl='https://ucbs.cevre.gov.tr/';
