import {services} from '@/lib/siteData';import {notFound} from 'next/navigation';import Link from 'next/link';import {Home,CheckCircle2,FileText,MapPinned} from 'lucide-react';
export function generateStaticParams(){return services.map(s=>({slug:s.slug}))}

const extras:Record<string,{work:string[];outputs:string[]}>={
'cevre-yonetimi':{work:['Yasal yükümlülük ve izin/lisans envanterinin çıkarılması','Saha kontrolleri, uygunsuzlukların kayıt altına alınması ve aksiyon takibi','Beyan, bildirim, ölçüm ve analiz takvimlerinin yönetilmesi','Resmî denetim hazırlığı ve doküman kontrolü'],outputs:['Yıllık çevre yönetim planı','Mevzuat ve izin/lisans takip tablosu','Saha kontrol ve uygunsuzluk kayıtları','Yönetim değerlendirme ve performans raporları']},
'ced-yonetimi':{work:['Yatırımın ÇED kapsamının ve eşiklerinin değerlendirilmesi','Proje Tanıtım Dosyası / ÇED dosyası hazırlık koordinasyonu','Kurum görüşleri, revizyonlar ve taahhütlerin takibi','Karar sonrası taahhütlerin işletme sistemine aktarılması'],outputs:['ÇED kapsam değerlendirme notu','Başvuru ve revizyon doküman seti','Taahhüt izleme listesi','Yatırım-işletme uyum kontrol kayıtları']},
'atiksu-yonetimi':{work:['Atıksu kaynaklarının ve deşarj noktalarının envanteri','Numune, analiz ve izin süreçlerinin planlanması','Arıtma tesisi performansının teknik olarak izlenmesi','Kaynakta azaltım ve geri kullanım fırsatlarının değerlendirilmesi'],outputs:['Atıksu akım şeması ve kaynak envanteri','Analiz/deşarj takip planı','Arıtma performans değerlendirmesi','İyileştirme ve geri kullanım aksiyon listesi']},
'atik-yonetimi':{work:['Atık kodlarının ve kaynaklarının doğrulanması','Geçici depolama alanları ve saha uygulamalarının kontrolü','Lisanslı taşıma/teslim süreçlerinin izlenmesi','Atık beyanı, kayıtlar ve azaltım projelerinin yönetimi'],outputs:['Atık envanteri ve kod listesi','Saha yerleşim/etiketleme kontrol listesi','Teslim ve beyan takip kayıtları','Atık azaltım ve geri kazanım önerileri']},
'tmgd':{work:['ADR kapsamı ve taraf rollerinin belirlenmesi','Ambalajlama, etiketleme, yükleme-boşaltma kontrolleri','Taşıma evrakı ve kayıt sisteminin kontrolü','Olay, kaza ve yıllık raporlama yükümlülüklerinin yönetimi'],outputs:['ADR kapsam ve görev matrisi','Saha kontrol kayıtları','Uygunsuzluk ve aksiyon listesi','Yıllık TMGD değerlendirme raporu']},
'kdu':{work:['Kimyasal envanter ve kullanım miktarlarının doğrulanması','GBF/SDS ve sınıflandırma bilgilerinin kontrol edilmesi','KKDİK/SEA yükümlülüklerinin değerlendirilmesi','Tedarikçi ve ürün bilgilerinin güncellik takibi'],outputs:['Kimyasal envanter','Mevzuat uygunluk değerlendirmesi','Eksik doküman ve aksiyon listesi','Tedarikçi/ürün takip kayıtları']},
'esg':{work:['Kuruma uygun ESG gösterge setinin belirlenmesi','Veri sahipliği ve doğrulama akışının kurulması','Risk, hedef ve performans göstergelerinin izlenmesi','Raporlama altyapısının hazırlanması'],outputs:['ESG gösterge kataloğu','Veri toplama ve sorumluluk matrisi','Risk/fırsat ve hedef tablosu','Yönetim raporlama paketi']},
'karbon-ayak-izi':{work:['Emisyon sınırlarının ve kaynaklarının belirlenmesi','Faaliyet verilerinin toplanması ve kalite kontrolü','Uygun emisyon faktörleriyle hesaplama','Azaltım senaryolarının ve yol haritasının hazırlanması'],outputs:['Sera gazı envanteri','Hesaplama dosyası ve veri kanıtları','Belirsizlik/veri kalitesi değerlendirmesi','Karbon azaltım yol haritası']},
'su-ayak-izi':{work:['Su kaynakları ve tüketim noktalarının haritalanması','Tüketim verilerinin ürün/proses bazında değerlendirilmesi','Havza ve su stresi risklerinin dikkate alınması','Azaltım ve geri kullanım hedeflerinin oluşturulması'],outputs:['Su kullanım envanteri','Su dengesi ve gösterge seti','Risk ve etki değerlendirmesi','Azaltım/geri kullanım hedef planı']},
'su-verimliligi':{work:['Sayaç ve proses bazlı su dengesi kurulması','Kayıp/kaçak ve gereksiz tüketim noktalarının bulunması','Teknik tasarruf ve yeniden kullanım projelerinin geliştirilmesi','Yatırım önceliği ve geri dönüş değerlendirmesi'],outputs:['Su verimliliği etüt özeti','Tasarruf potansiyeli listesi','Teknik aksiyon ve yatırım planı','İzleme göstergeleri']},
'enerji-yonetimi':{work:['Enerji tüketim profilinin proses/ekipman bazında çıkarılması','Önemli enerji kullanım alanlarının belirlenmesi','Verimlilik fırsatlarının teknik-ekonomik değerlendirilmesi','Hedef, gösterge ve sürekli iyileştirme sisteminin kurulması'],outputs:['Enerji profili ve baz çizgi','Önemli enerji kullanımları listesi','Verimlilik proje portföyü','Enerji performans takip göstergeleri']}
};

export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const s=services.find(x=>x.slug===slug);if(!s)notFound();const Icon=s.icon;const extra=extras[s.slug]||{work:[],outputs:[]};return <main className="article-page"><div className="service-top"><a href="/" className="brand"><img src="/logo.png" alt="ARYA ECY"/></a><Link href="/" className="home-return"><Home size={17}/> Ana Ekrana Dön</Link></div><section className="service-detail v26-service-detail"><article className="service-detail-copy"><span>ARYA ECY • Hizmetler</span><Icon size={38}/><h1>{s.title}</h1><p className="lead">{s.intro}</p>{s.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<section><h2>Çalışmanın sahadaki kapsamı</h2><div className="service-list">{extra.work.map(x=><div key={x}><CheckCircle2 size={17}/><span>{x}</span></div>)}</div></section><section><h2>Çalışma çıktıları</h2><div className="service-list outputs">{extra.outputs.map(x=><div key={x}><FileText size={17}/><span>{x}</span></div>)}</div></section><h2>ARYA ECY ile hizmetin yönetimi</h2><p>Çalışma başlangıcında mevcut durum, yasal yükümlülükler, saha koşulları ve kurum içi sorumluluklar birlikte değerlendirilir. Bulgular yalnızca raporlanmaz; uygulanabilir aksiyonlara dönüştürülür, sorumlular ve terminler belirlenir, tamamlanma durumu izlenir. Değişen faaliyetler ve mevzuat gereklilikleri periyodik kontrollerle sisteme dahil edilir.</p><h2>Dokümantasyon ve izlenebilirlik</h2><p>İzinler, beyanlar, ölçüm ve analiz sonuçları, saha kayıtları, eğitimler ve ilgili resmi yazışmalar düzenli bir kayıt yapısında takip edilir. Böylece geçmiş işlemlere erişim kolaylaşır, yaklaşan yükümlülükler zamanında görülür ve resmi denetimlerde ihtiyaç duyulan kanıtlar daha hızlı sunulabilir.</p><div className="detail-note"><b>Sonuç odaklı yaklaşım</b><p>Hedefimiz yalnızca bir yükümlülüğü tamamlamak değil; işletmede sürdürülebilir, ölçülebilir, denetlenebilir ve günlük operasyonla uyumlu bir yönetim sistemi oluşturmaktır.</p></div></article><aside className="service-detail-visual"><img src="/environment-hero.png" alt={`${s.title} hizmeti - ARYA ECY`}/><div><MapPinned size={20}/><b>{s.title}</b><span>Uzman ekip • saha uygulaması • mevzuat uyumu • ölçülebilir çıktı • sürekli iyileştirme</span></div></aside></section></main>}
