'use client';
import {useEffect,useMemo,useState} from 'react';import Navbar from '@/components/Navbar';import {adminCareerList,adminList,deleteCareerApplication,deleteContent,saveContent,signInAdmin,uploadMedia,uploadPdf,SiteContent,ContentType,CareerApplication} from '@/lib/cms';import {BookOpen,Info,MessageSquare,FileText,Newspaper,ContactRound,BriefcaseBusiness} from 'lucide-react';
const blank:SiteContent={type:'article',title:'',title_en:'',excerpt:'',excerpt_en:'',body:'',body_en:'',image_url:'',file_url:'',published:false,sort_order:0,category:'',subcategory:''};
type Module=ContentType|'career';
const labels:Partial<Record<ContentType,string>>={article:'Kütüphane Makalesi',announcement:'Duyuru',news:'Bizden Haberler',about:'Hakkımızda',regulation:'Mevzuat PDF',contact:'İletişim'};
const cards=[{type:'about' as Module,label:'Hakkımızda',icon:Info},{type:'news' as Module,label:'Bizden Haberler',icon:Newspaper},{type:'announcement' as Module,label:'Duyurular',icon:MessageSquare},{type:'article' as Module,label:'Kütüphane',icon:BookOpen},{type:'regulation' as Module,label:'Mevzuat',icon:FileText},{type:'contact' as Module,label:'İletişim',icon:ContactRound},{type:'career' as Module,label:'Kariyer Başvuruları',icon:BriefcaseBusiness}];
export default function Admin(){
 const [token,setToken]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [err,setErr]=useState('');const [items,setItems]=useState<SiteContent[]>([]);const [career,setCareer]=useState<CareerApplication[]>([]);const [form,setForm]=useState<SiteContent>(blank);const [active,setActive]=useState<Module>('article');const [uploading,setUploading]=useState(false);
 const load=(t=token)=>{adminList(t).then(setItems).catch(e=>setErr(e.message));adminCareerList(t).then(setCareer).catch(()=>{})};
 useEffect(()=>{const t=sessionStorage.getItem('arya_admin_token')||'';if(t){setToken(t);load(t)}},[]);
 async function login(e:React.FormEvent){e.preventDefault();setErr('');try{const d=await signInAdmin(email,password);setToken(d.access_token);sessionStorage.setItem('arya_admin_token',d.access_token);load(d.access_token)}catch(e:any){setErr(e.message)}}
 async function save(e:React.FormEvent){e.preventDefault();if(active==='career')return;setErr('');try{await saveContent(token,{...form,type:active as ContentType});setForm({...blank,type:active as ContentType});load()}catch(e:any){setErr(e.message)}}
 async function pdf(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setErr('');try{const file_url=await uploadPdf(token,file);setForm(f=>({...f,file_url}))}catch(e:any){setErr(e.message)}finally{setUploading(false)}}
 async function media(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(true);setErr('');try{const image_url=await uploadMedia(token,file);setForm(f=>({...f,image_url}))}catch(e:any){setErr(e.message)}finally{setUploading(false)}}
 const filtered=useMemo(()=>active==='career'?[]:items.filter(x=>x.type===active),[items,active]);
 const select=(type:Module)=>{setActive(type);if(type!=='career')setForm({...blank,type:type as ContentType});setErr('')};
 if(!token)return <main className="article-page"><Navbar/><div className="admin-login-page"><span>ARYA A.Ş.</span><h1>Yönetim Giriş</h1><p>Bu alan yalnızca yetkili ARYA A.Ş. kullanıcıları içindir.</p><form onSubmit={login}><input placeholder="E-posta" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Şifre" value={password} onChange={e=>setPassword(e.target.value)}/><button>Giriş Yap</button>{err&&<b className="error">{err}</b>}</form></div></main>;
 return <main className="article-page"><Navbar/><section className="admin-page v24-admin"><div className="admin-head"><div><span>ARYA A.Ş.</span><h1>Web İçerik Yönetimi</h1><p>Web sitesi içerikleri, iletişim bilgileri ve kariyer başvuruları tek merkezden yönetilir.</p></div><button onClick={()=>{sessionStorage.removeItem('arya_admin_token');location.reload()}}>Çıkış</button></div>
 <div className="admin-module-grid">{cards.map(c=>{const Icon=c.icon;const count=c.type==='career'?career.length:items.filter(x=>x.type===c.type).length;return <button key={c.type} className={active===c.type?'active':''} onClick={()=>select(c.type)}><Icon size={21}/><span>{c.label}</span><small>{count} kayıt</small></button>})}</div>
 {active==='career'?<section className="career-admin"><h2>Kariyer Başvuruları</h2>{career.length?career.map(x=><article key={x.id}><div><small>{x.application_type==='internship'?'STAJ':'İŞ'} · {x.created_at?new Date(x.created_at).toLocaleDateString('tr-TR'):''}</small><h3>{x.full_name}</h3><p><b>E-posta:</b> {x.email} · <b>Telefon:</b> {x.phone||'-'} · <b>Şehir:</b> {x.city||'-'}</p><p><b>Eğitim:</b> {x.education||'-'}</p>{x.experience&&<p><b>Deneyim:</b> {x.experience}</p>}{x.linkedin_url&&<p><a href={x.linkedin_url} target="_blank" rel="noreferrer">LinkedIn ↗</a></p>}{x.message&&<p><b>Not:</b> {x.message}</p>}</div><button className="danger" onClick={async()=>{if(x.id&&confirm('Başvuru silinsin mi?')){await deleteCareerApplication(token,x.id);load()}}}>Sil</button></article>):<div className="empty-card">Henüz kariyer başvurusu yok.</div>}</section>:<div className="admin-grid"><form className="editor" onSubmit={save}><h2>{form.id?'İçeriği Düzenle':`Yeni ${labels[active as ContentType]||'İçerik'}`}</h2>
 {active==='contact'?<><label>Şirket / Başlık<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>E-posta<input type="email" value={form.excerpt||''} onChange={e=>setForm({...form,excerpt:e.target.value})} required/></label><label>Telefon<input value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Adres (TR)<textarea rows={4} value={form.body||''} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Address (EN)<textarea rows={4} value={form.body_en||''} onChange={e=>setForm({...form,body_en:e.target.value})}/></label><label>Web sitesi<input value={form.subcategory||''} onChange={e=>setForm({...form,subcategory:e.target.value})}/></label></>:<><label>Başlık (TR)<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Title (EN)<input value={form.title_en||''} onChange={e=>setForm({...form,title_en:e.target.value})}/></label>{active!=='about'&&<><label>Kısa açıklama (TR)<textarea rows={3} value={form.excerpt||''} onChange={e=>setForm({...form,excerpt:e.target.value})}/></label><label>Short description (EN)<textarea rows={3} value={form.excerpt_en||''} onChange={e=>setForm({...form,excerpt_en:e.target.value})}/></label></>}{active!=='regulation'&&<><label>İçerik (TR)<textarea rows={active==='about'?9:7} value={form.body||''} onChange={e=>setForm({...form,body:e.target.value})}/></label><label>Content (EN)<textarea rows={active==='about'?9:7} value={form.body_en||''} onChange={e=>setForm({...form,body_en:e.target.value})}/></label></>}{['article','announcement','news'].includes(active)&&<><label>Görsel veya Video Yükle<input type="file" accept="image/png,image/jpeg,image/webp,video/mp4,video/webm" onChange={media}/></label>{uploading&&<small>Dosya yükleniyor...</small>}<label>Görsel / Video URL<input value={form.image_url||''} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="Yükleme sonrası otomatik dolar"/></label></>}{active==='regulation'&&<><label>Mevzuat Ana Bölümü<input value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Örn. ÇEVRE YÖNETİMİ MEVZUATI" required/></label><label>Alt Bölüm<input value={form.subcategory||''} onChange={e=>setForm({...form,subcategory:e.target.value})} placeholder="Örn. Çevre Yönetmeliği" required/></label><label>Sıra No<input type="number" min="0" value={form.sort_order??0} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label>PDF Yükle<input type="file" accept="application/pdf,.pdf" onChange={pdf}/></label>{uploading&&<small>PDF yükleniyor...</small>}<label>PDF URL<input value={form.file_url||''} onChange={e=>setForm({...form,file_url:e.target.value})}/></label></>}</>}
 <label className="check"><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Yayına al</label><div className="editor-actions"><button>Kaydet</button><button type="button" className="secondary" onClick={()=>setForm({...blank,type:active as ContentType})}>Temizle</button></div>{err&&<b className="error">{err}</b>}</form>
 <div className="content-list"><h2>{labels[active as ContentType]} İçerikleri</h2>{filtered.length?filtered.map(x=><div className="content-row" key={x.id}><div><small>{x.published?'YAYINDA':'TASLAK'}</small><b>{x.title}</b>{x.file_url&&<span>PDF hazır</span>}{x.image_url&&<span>Medya hazır</span>}</div><div><button onClick={()=>setForm(x)}>Düzenle</button><button className="danger" onClick={async()=>{if(confirm('Silinsin mi?')){await deleteContent(token,x.id!);load()}}}>Sil</button></div></div>):<div className="empty-card">Bu bölümde henüz içerik yok.</div>}</div></div>}
 </section></main>}
