export const serviceEnglish:Record<string,{title:string;summary:string;intro:string;highlight:string}>={
 'cevre-yonetimi':{title:'Environmental Management Consultancy',summary:'Integrated management of environmental legislation, permits, declarations, field controls, audits and environmental performance.',intro:'Environmental management is more than filing declarations. ARYA ECY connects regulatory obligations with real field conditions, operational responsibilities and measurable performance.',highlight:'We manage regulation at the desk, implementation in the field and evidence in the management system.'},
 'ced-yonetimi':{title:'EIA Management Consultancy',summary:'End-to-end management of Environmental Impact Assessment scope for new investments, capacity increases and process changes.',intro:'A well-designed EIA process protects project schedules and future permits. We assess the investment with technical data and align environmental commitments with implementation.',highlight:'We manage investment decisions and environmental obligations on the same table.'},
 'atiksu-yonetimi':{title:'Wastewater Management Consultancy',summary:'Technical management of wastewater sources, treatment performance, analyses, discharge conditions and reuse opportunities.',intro:'Effective wastewater management starts at the process, not at the discharge point. We analyse sources, variability, treatment performance and reuse potential together.',highlight:'We look for the cause of the problem in the process, not only at the outlet.'},
 'atik-yonetimi':{title:'Waste Management Consultancy',summary:'Traceable management from waste generation and segregation to storage, transport, recovery, disposal, records and declarations.',intro:'Waste management is not just assigning a code and sending waste away. We build a field-ready system that combines compliance, safety, traceability, cost and resource efficiency.',highlight:'We manage waste together with its source, risk, cost and recovery value.'},
 'tmgd':{title:'Dangerous Goods Safety Adviser Consultancy',summary:'ADR-focused dangerous goods compliance, field controls, documentation, training and operational risk management.',intro:'We turn dangerous goods obligations into practical controls across transport, loading, unloading, storage and documentation processes.',highlight:'We turn ADR compliance into a daily operational discipline.'},
 'kdu':{title:'Chemical Assessment Consultancy',summary:'Chemical inventory, SDS controls, storage compatibility and obligation tracking for safe and compliant chemical management.',intro:'Chemical compliance begins with knowing what is used, where it is stored and which obligations it triggers. We establish a traceable chemical management structure.',highlight:'We keep chemical data inside the decision-making process, not on shelves.'},
 'esg':{title:'ESG Consultancy',summary:'Data ownership, targets, performance monitoring and reporting infrastructure for environmental, social and governance indicators.',intro:'ESG becomes useful when indicators, evidence and responsibilities are embedded into management decisions. We establish that structure before reporting.',highlight:'We build ESG as a data and management discipline before it becomes a report.'},
 'karbon-ayak-izi':{title:'Carbon Footprint Consultancy',summary:'Corporate greenhouse gas inventory, data quality, calculation, verification readiness and emissions reduction roadmap.',intro:'A carbon footprint should show not only how much is emitted, but also where emissions originate and which projects can reduce them effectively.',highlight:'We turn carbon accounting from a result table into reduction decisions.'},
 'su-ayak-izi':{title:'Water Footprint Consultancy',summary:'Assessment of water use by quantity, source, basin risk and environmental impact.',intro:'The same water consumption can have different environmental significance in different locations. We evaluate consumption together with process needs and basin conditions.',highlight:'We manage water together with the value and risk of the basin where it is used.'},
 'su-verimliligi':{title:'Water Efficiency Consultancy',summary:'Reducing water consumption, preventing losses, optimising processes and developing reuse opportunities.',intro:'Real water savings come from understanding why water is consumed. We analyse use by process and convert technical opportunities into practical actions.',highlight:'For every cubic metre, we ask where it is used, why it is used and how it can be reduced.'},
 'enerji-yonetimi':{title:'Energy Management Consultancy',summary:'Process-based energy monitoring, identification of significant energy uses and management of efficiency opportunities.',intro:'Energy management is more than tracking bills. We connect consumption with production, equipment operation and process conditions to identify real efficiency opportunities.',highlight:'We manage energy in the process, not only on the invoice.'}
};
export const englishServiceSections=(title:string)=>[
 ['Scope and current-state assessment',`We define the operational scope of ${title.toLowerCase()} and review existing processes, records, permits, field conditions and responsibilities.`],
 ['Compliance and risk review','Applicable obligations and technical risks are mapped, prioritised and converted into clear actions with owners and deadlines.'],
 ['Field implementation','Controls are designed around real operating conditions so that procedures, equipment, records and employee practices work together.'],
 ['Data, evidence and performance','Key data and supporting evidence are standardised to make performance measurable, traceable and ready for internal or external review.'],
 ['Improvement and management reporting','Findings are converted into practical improvement projects and concise management reporting for sustainable follow-up.']
];
