'use client';
import {useEffect,useState} from 'react';import {getPublished,getPublishedNews,SiteContent} from '@/lib/cms';import {useLanguage} from '@/components/LanguageProvider';
const announcements=[{title:'Çevre mevzuatı, beyan dönemleri ve güncel yükümlülükler için duyurularımızı takip edin.'}];
const pick=(x:SiteContent|undefined,lang:'tr'|'en',field:'title'|'excerpt')=>{if(!x)return '';if(lang==='en'){const key=field==='title'?'title_en':'excerpt_en';return (x[key] as string)||x[field]||''}return x[field]||''};
export default function HomeCards(){const {lang}=useLanguage();const en=lang==='en';const [duy,setDuy]=useState<any[]>(announcements);const [news,setNews]=useState<SiteContent[]>([]);useEffect(()=>{getPublished('announcement').then(x=>x.length&&setDuy(x.slice(0,3)));getPublishedNews().then(x=>setNews(x.slice(0,3)));},[]);return <section className="final-cards">
<a className="home-card-link" href="/duyurular"><article><h2>{en?'ANNOUNCEMENTS':'DUYURULAR'} <span>→</span></h2>{duy.slice(0,3).map((x:any,i)=><p key={x.id||i}>◆ <span>{en?(x.title_en||x.title):x.title}</span></p>)}<b className="card-cta">{en?'View all announcements':'Tüm duyuruları görüntüle'}</b></article></a>
<a className="home-card-link" href="/haberler"><article><h2>{en?'FROM ARYA':'BİZDEN HABERLER'} <span>→</span></h2>{(news.length?news:[{title:'Sürdürülebilir yarınlar için çalışmaya devam ediyoruz',title_en:'We keep working for a sustainable future'}] as SiteContent[]).slice(0,3).map((x,i)=><p key={x.id||i}>◆ <span>{pick(x,lang,'title')}</span></p>)}<b className="card-cta">{en?'View all news':'Tüm haberleri görüntüle'}</b></article></a>
<a className="home-card-link" href="/kariyer"><article><h2>{en?'CAREERS':'KARİYER'} <span>→</span></h2><p>◆ <span>{en?'Join ARYA ECY through internship or job applications.':'Staj veya iş başvurunuzu ARYA ECY kariyer formu üzerinden bize iletin.'}</span></p><b className="card-cta">{en?'Open application form':'Başvuru formunu aç'}</b></article></a>
</section>}
