'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {getPublished,SiteContent} from '@/lib/cms';import {X,AlertTriangle} from 'lucide-react';
const fallbackAnnouncements=[{title:'Çevre mevzuatı, beyan dönemleri ve güncel yükümlülükler için duyurularımızı takip edin.'}];
const fallbackImportant:SiteContent={id:'fallback-important',type:'important',title:'Önemli Bilgilendirmeler',excerpt:'Kritik duyuru ve güncel bilgilendirmeler bu alanda yayınlanacaktır.',body:'ARYA yönetim panelinden “Önemli” içerik yayınlandığında bu kutu otomatik olarak güncellenir.',published:true,created_at:new Date(0).toISOString()};
export function AnnouncementTicker(){const [items,setItems]=useState<any[]>(fallbackAnnouncements);useEffect(()=>{getPublished('announcement').then(x=>x.length&&setItems(x));},[]);return <div className="announcement-bar"><strong>Duyurular</strong><div className="announcement-window"><div className="announcement-track">{items.map((x,i)=><span key={x.id||i}>{x.title}</span>)}</div></div></div>}
export function HomeAbout(){const [item,setItem]=useState<SiteContent|null>(null);useEffect(()=>{getPublished('about').then(x=>setItem(x[0]||null));},[]);return <section id="hakkimizda" className="home-about"><span>ARYA Entegre Çevre Yönetimi</span><h1>{item?.title||'Çevre yönetimini sahada, mevzuatta ve sürdürülebilirlikte birlikte yönetiyoruz.'}</h1><p>{item?.body||item?.excerpt||'İşletmelerin çevresel yükümlülüklerini sadece takip etmiyor; sahadaki uygulamalarla birlikte planlıyor, ölçüyor ve sürdürülebilir bir yönetim sistemine dönüştürüyoruz.'}</p></section>}
export function ImportantPopup(){const [item,setItem]=useState<SiteContent>(fallbackImportant);const [open,setOpen]=useState(true);useEffect(()=>{getPublished('important').then(x=>{if(x[0])setItem(x[0])}).catch(()=>{});},[]);if(!open)return <button className="important-reopen" onClick={()=>setOpen(true)} aria-label="Önemli bilgilendirmeyi aç"><AlertTriangle size={18}/><span>Önemli</span></button>;return <aside className="important-popup v26-important"><button aria-label="Kapat" onClick={()=>setOpen(false)}><X size={16}/></button><div className="important-icon"><AlertTriangle size={20}/></div><small>ÖNEMLİ</small><b>{item.title}</b>{item.excerpt&&<p>{item.excerpt}</p>}{item.body&&<details><summary>Detayı gör</summary><p>{item.body}</p></details>}</aside>}
export function HomeAd(){const [ad,setAd]=useState<SiteContent|null>(null);useEffect(()=>{getPublished('ad').then(x=>setAd(x[0]||null));},[]);if(!ad)return null;return <div className="home-ad"><small>Güncel</small><b>{ad.title}</b><span>{ad.excerpt}</span></div>}
export function LibraryTeaser(){const [items,setItems]=useState<SiteContent[]>([]);useEffect(()=>{getPublished('article').then(x=>setItems(x.slice(0,3)));},[]);if(!items.length)return null;return <div className="library-teaser"><b>Kütüphaneden</b>{items.map(x=><Link key={x.id} href={`/kutuphane/${x.id}`}>{x.title}</Link>)}</div>}
